<?php

namespace indexBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ubicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ubicacionRepository extends EntityRepository
{
}
